language: objective-c
osx_image: xcode611
before_install:
- gem install xcpretty
script:
- set -o pipefail
- xcodebuild -project Alamofire.xcodeproj -scheme Alamofire test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- xcodebuild -project "iOS Example.xcodeproj" -scheme "iOS Example" build -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES | xcpretty -c
